### PR TITLE
Updated README.md and removed 3 repositories  not accepting pull requests anymore for hacktoberfest 2020

### PR DESCRIPTION
**Pull request by shraiyya**

### CODE REVIEW

**Review by OtacilioN — COMMENTED** [review]
Are you sure that https://github.com/OpenSourceTogether/Hacktoberfest-2020 is not accepting pull requests?

**Comment by shraiyya** [comment]
Yes. I have checked.

**Comment by shraiyya** [comment]
https://github.com/OpenSourceTogether/Hacktoberfest-2020/issues/146

**Review by OtacilioN — APPROVED** [review]
Awesome, thanks for contributing!

**Comment by chandan-reddy-k** [comment]
@shraiyya @OtacilioN 

https://github.com/OpenSourceTogether/Hacktoberfest-2020 

Will continue to accept PRs to provide a learning opportunity for beginners, though pull requests will not be counted towards for hacktoberfest challenge.

**Comment by OtacilioN** [comment]
I think we can create a new section called "training-not-couting" with a disclaimer that those repositories are not counting to hacktoberfest.

**Pull request merged**
