### PR TITLE
Removed Simple Contribute form the list 

### PR DESCRIPTION
**Pull request by IMVraj**
## Contributing

If you want to add a project to this list, please make sure that:

- [X] You read the [contributing guide](#CONTRIBUTING.md)
- [X] The project can't be just an "add your name" or simply + 1 contribution to hacktoberfest
- [X] Place them in alphabetical order
- [X] One repository per PR/contribution - _avoid conflicts and simplify review_
- [X] Your pull request is not spammy just adding an empty line, otherwise it will be marked as invalid and not count to hacktoberfest.

If they meet the requirements above, feel free to create a PR. Happy Hacking! :sparkles:

### CODE REVIEW

**Review by OtacilioN — APPROVED** [review]
Awesome, thanks for contributing!

**Comment by IMVraj** [comment]
If you had a look at the new rules, our pull requests will have to be labeled "hacktoberfest-accepted" in order to be valid. I hope you won't mind doing that.

**Comment by OtacilioN** [comment]
Hey @IMVraj can you send me the link or reference where you read this?

**Comment by OtacilioN** [comment]
Okay found it! https://hacktoberfest.digitalocean.com/hacktoberfest-update it says that can be the label or the entire repository classified as hacktoberfest topic, I will add the topic so every pr will count.

**Comment by OtacilioN** [comment]
Actually we already have hacktoberfest as topic

**Pull request merged**
