### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fant0me**
font changed to italic.

## Contributing

If you want to add a project to this list, please make sure that:

- [x] You read the [contributing guide](#CONTRIBUTING.md)
- [x] The project can't be just an "add your name" or simply + 1 contribution to hacktoberfest
- [x] Place them in alphabetical order
- [x] One repository per PR/contribution - _avoid conflicts and simplify review_
- [x] Your pull request is not spammy just adding an empty line, otherwise it will be marked as invalid and not count to hacktoberfest.

If they meet the requirements above, feel free to create a PR. Happy Hacking! :sparkles:

### CODE REVIEW

**Review by fant0me — COMMENTED** [review]
heading changed

**Comment by OtacilioN** [comment]
I'm not sure if it's a valid contribution, so help me with these questions:

> what benefit will we have with this change? Why would it be better this way?
> Why haven't you applied to all headings?

**Comment by fant0me** [comment]
I will apply to all the headings.

**Comment by OtacilioN** [comment]
Okay, but what benefit will we have with this change? Why would it be better this way?

**Comment by fant0me** [comment]
It will change the look.
I am new to this and trying to learn how to contribute so starting from
this.

**Pull request closed without merging**
